version: "3.9"
services:
  local-redis:
    image: redis:latest
    container_name: rds
    ports:
      - "6379:6379"
    networks:
      infra-kubernetes:
   local-postgres:
    image: postgres:latest
    container_name: pg-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: adminpg
      POSTGRES_DB: dbtest
    networks:
      infra-kubernetes:
   local-app-java:
    image: dberrocal/kbn:01
    ports:
      - "80:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=test1,test2,test3" 
      - "DATABASE_REDIS_URL=192.168.1.23"
    networks:
      infra-kubernetes: 
networks:
  infra-kubernetes:
   
