version: "3.9"
services:
  local-redis:
    image: redis:latest
    container_name: rds
    ports:
      - "6379:6379"
    networks:
      infra-kubernetes:
   local-postgres:
    image: postgres:latest
    container_name: pg-local
    ports:
      - "5432:5432"
    networks:
      infra-kubernetes:
networks:
  infra-kubernetes:
   
