version: "3.9"
services:
  local-app-java:
    image: dberrocal/kbn:01
    ports:
      - "80:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=test1,test2,test3" 
      - "DATABASE_REDIS_URL=rds"
   
