apiVersion: v1
kind: Pod
metadata:
  name: postgres-k8
spec:
  containers:
    - image: postgres:latest
      name: pg-local
      ports:
        - containerPort: 5432
          name: http
          protocol: TCP