apiVersion: v1
kind: Pod
metadata:
  name: spring-test
spec:
  containers:
    - image: dberrocal/kbn:01
      name: springtest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP